name: Windows CI

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build_and_test:
    name: Build and Check
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore MyParser.sln

      - name: Check Code Style
        run: dotnet format MyParser.sln --verify-no-changes --verbosity diagnostic

      - name: Build
        run: dotnet build MyParser.sln --configuration Release --no-restore

      - name: Test
        run: dotnet test MyParser.sln --configuration Release --no-build --verbosity normal





